### ISSUE TITLE
Nullish Coalescing (Stage 3)

### ISSUE THREAD

**Issue by hzoo** [babel/proposals#14]
Champions: @gisenberg
Spec Repo: https://github.com/gisenberg/proposal-nullary-coalescing
First presented at the [July 2017](https://github.com/tc39/agendas/blob/master/2017/07.md) meeting: [slides](https://docs.google.com/presentation/d/1m5nxTH8ifcmOlyaTmTuMAa1bawiGUyKJzQGlw-EVSKM/edit)
Moved to Stage 1 at the [Sept 2017](https://github.com/tc39/agendas/blob/master/2017/09.md) meeting: [slides](https://docs.google.com/presentation/d/1m5nxTH8ifcmOlyaTmTuMAa1bawiGUyKJzQGlw-EVSKM/edit?usp=sharing)

Syntax

```js
a ?? b
```

> When performing optional property access in a nested structure in conjunction with the optional chaining operator, it is often desired to provide a default value if the result of that property access is null or undefined. At present, a typical way to express this intent in JavaScript is by using the || operator.

so most use `const variable = a || b` but a falsy value like `0 or '' or false` will unintentionally return `b` as the value.

Notes:

> While this proposal specifically calls out null and undefined values, the intent is to provide a complementary operator to the [optional chaining operator](https://github.com/TC39/proposal-optional-chaining). This proposal will update to match the semantics of that operator.

## Parsing

- [ ] a new node type name (operator)?
- [ ] pluginName?

https://twitter.com/littledan/status/908032146484469761
https://github.com/babel/babylon/pull/742/files#r142008197

**Comment by jridgewell** [comment]
`logicalCOALESCE`? Too much of a mouthful? `logicalQQ`?

**Comment by gisenberg** [comment]
I started referring to this as the existential operator in the slides.

**Comment by hzoo** [comment]
@gisenberg feel free to edit the title/etc (if your in the tc39 team it gives you write access to this repo)

**Comment by ljharb** [comment]
(see https://github.com/gisenberg/proposal-nullary-coalescing/issues/3)

**Comment by azz** [comment]
Parser PR: babel/babylon#761, follow-up: babel/babylon#762
Transform PR: babel/babel#6483

**Comment by vjpr** [comment]
What is the status of this? Is it ready to use?

**Comment by azz** [comment]
Yes, just enable the `@babel/plugin-proposal-nullish-coalescing-operator` plugin.

https://www.npmjs.com/package/@babel/plugin-proposal-nullish-coalescing-operator

**Comment by hzoo** [comment]
Yep https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-nullish-coalescing-operator
