### ISSUE TITLE
Optional Chaining Operator (Stage 1)

### ISSUE THREAD

**Issue by hzoo** [babel/proposals#18]
Champion: @gisenberg 
Spec Repo: https://github.com/gisenberg/proposal-optional-chaining
Stayed at Stage 1 at the [July 2017 meeting](https://github.com/tc39/agendas/blob/master/2017/07.md): https://docs.google.com/presentation/d/1OcytQtyykmOZJwm-LFgOP0FpQccyeajAjLdOvBki9a0/
Stayed at Stage 1 at the [Sept 2017 meeting](https://github.com/tc39/agendas/blob/master/2017/09.md): https://docs.google.com/presentation/d/1iiCtJSW42Z7lg0YlagOZOfI-FTrkN88OuiO3pySawSo/edit?usp=sharing

Syntax

```js
a?.b
```

## Implementation

- https://github.com/babel/babel/pull/5813
- As part of https://github.com/babel/babel/releases/tag/v7.0.0-alpha.15
- Test https://babeljs.io/7/

**Comment by littledan** [comment]
Note that the issue of contention at TC39 was the "short-circuiting" semantics. See this issue for details: https://github.com/tc39/proposal-optional-chaining/issues/10 . Previously, the specification was option 4. The specification was changed to option 2 based on online feedback.

The committee seemed to be advocating option 1, but it's unclear if they had a good understanding of the CoffeeScript data or the way other programming languages work here.

These differences matter for both parsing and the transform, though there may be some design that handles the parsing in a single way among all options.

**Comment by hzoo** [comment]
@littledan if it moves the proposal forward (worth implementing both for someone) we could have options - to convince people one is better than the other.

**Comment by ljharb** [comment]
The only concern there is that it turns a likelihood of someone shipping untranspiled code using eventually-wrong semantics into a certainty.

**Comment by hzoo** [comment]
@ljharb this is for stage-0, and we are happy to break whenever if we aren't sure of the semantics. Maybe in these cases we have a warning. I don't think we do need to implement both actually, just show the input/output

**Comment by littledan** [comment]
I don't see this as having a higher risk than many of the other proposals that Babel has implemented at Stage 1. I think @hzoo has done a good job communicating clearly that Stage 1 and 2 are highly unstable.

**Comment by littledan** [comment]
Anyway, I'm not sure if anyone would really use the various alternatives, it just might be an interesting way to get feedback.

**Comment by hzoo** [comment]
Yeah and if we do implement multiple versions, it's definetely not an intention in any way to be used other than for feedback for the proposal itself.

**Comment by morsmodr** [comment]
Is there any progress in this? Currently from here: https://github.com/babel/proposals I see that the Readme.md has not been updated in a long while. The proposal is in stage 4 which means it should be part of preset-env but as per the proposals link I shared, optional chaining is supposed to be in babel-preset-stage-1?

Is there a way to confirm this has indeed been added to preset-env?

**Comment by JLHwung** [comment]
> it should be part of preset-env 

Yes, optional-chaining is already included in `@babel/preset-env` 7.12. Please refer to TC39 proposals repo for latest status: https://github.com/tc39/proposals the Babel proposals repo may be out of date.

Closing this issue as it has been supported by `@babel/preset-env`
