### ISSUE TITLE
Nov 2017

### ISSUE THREAD

**Issue by hzoo** [babel/proposals#34]
> Airbnb: San Francisco, CA (Nov 28-30)
> https://github.com/tc39/agendas/blob/master/2017/11.md

> Checkbox means we completed it (some Stage 1 we may want to wait to start, given instability of the proposal)
> https://tc39.github.io/process-document/ for a primer what each Stage means

> Meeting notes: https://github.com/rwaldron/tc39-notes/tree/master/es8/2017-11

### New Proposals
- [x] HashBang Directive (`#! node foo`) to Stage 1
- `Object.freeze` + `Object.seal` syntax to Stage 1
- [x] Block Params to Stage 1

### Moving Forward

- Numeric Separators (`1_000`) from Stage 2 to Stage 3
- RegExp dotAll to Stage 4
- RegExp named captures to Stage 4
- Class Fields split into class instance fields and private instance methods to Stage 3
  - so `class A { a = 1; #b = c; #a() {} }`

### Needs Spec Work

- Class Fields split public + private static fields and private static methods to Stage 2
  - so `class A { static a = 1; static #b = c; static #a() {} }`

### Other (Builtins, etc)

- `Array.prototype.flatten` to Stage 3
- `Array.prototype.flatMap` to Stage 3
- `String.prototype.replaceAll` to Stage 1
- Subsume JSON to Stage 2
- `String.prototype.codePoints` to Stage 1
- Distinguishing literal strings to Stage 1

**Comment by jridgewell** [comment]
`Array.prototype.flatten` & `Array.prototype.flatMap` to Stage 3.

**Comment by jridgewell** [comment]
Numeric separators to Stage 3 https://github.com/tc39/proposal-numeric-separator

**Comment by jridgewell** [comment]
HashBangs to Stage 1. https://gist.github.com/bmeck/59cf8c16959eccffd8b7e9828826a842

**Comment by jridgewell** [comment]
String.prototype.replaceAll for Stage 1. https://github.com/psmarshall/string-replace-all-proposal

**Comment by jridgewell** [comment]
Subsume JSON to Stage 2. https://github.com/tc39/proposal-json-superset

**Comment by jridgewell** [comment]
RegExp dotAll to Stage 4. https://github.com/tc39/proposal-regexp-dotall-flag

**Comment by jridgewell** [comment]
RegExp named captures to Stage 4. https://github.com/tc39/proposal-regexp-named-groups

**Comment by ljharb** [comment]
(Those last two are conditional on the spec PR being approved by the editor)

**Comment by chicoxyzzy** [comment]
String.prototype.codePoints to Stage 1. https://github.com/RReverser/string-prototype-codepoints

**Comment by chicoxyzzy** [comment]
Distinguishing literal strings to Stage 1. https://github.com/mikewest/tc39-proposal-literals

**Comment by chicoxyzzy** [comment]
Class Fields down to Stage 2. https://github.com/tc39/proposal-class-fields

**Comment by ljharb** [comment]
(TC39 folks will comment more on Class Fields after post-committee discussion tonight; please withhold comment until then)

**Comment by jridgewell** [comment]
Object.freeze + Object.seal syntax to Stage 1. https://github.com/keithamus/object-freeze-seal-syntax

**Comment by jridgewell** [comment]
Block Params to Stage 1. https://github.com/samuelgoto/proposal-block-params

**Comment by jridgewell** [comment]
Class fields and private methods will be merged, and split.

Class instance fields (public and private), and private instance methods are now one proposal, and at Stage 3.

Class static fields (public and private), and private static methods are now a second proposal, and at Stage 2.
