### ISSUE TITLE
April 2021

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/proposals#72]
Agenda: https://github.com/tc39/agendas/blob/master/2021/04.md

**Comment by nicolo-ribaudo** [comment]
Class fields, private methods, and static class features are Stage 4 :tada:

**Comment by nicolo-ribaudo** [comment]
Closing this since https://github.com/babel/proposals/issues/73 has more links

**Comment by jridgewell** [comment]
Oh, I didn't notice this one. Sorry!
