### ISSUE TITLE
May 2023

### ISSUE THREAD

**Issue by jridgewell** [babel/proposals#88]
https://github.com/tc39/agendas/blob/main/2023/05.md

**Comment by jridgewell** [comment]
_needs consensus: https://github.com/tc39/ecma262/pull/3052 limit ArrayBuffer size to 2^53 bytes ([slides](https://docs.google.com/presentation/d/1WR9xgfauXkswMK5Td4NHU8GEpJtdfV_yyA-_gviL7pk))_ reaches consensus

**Comment by jridgewell** [comment]
_[Array.fromAsync](https://github.com/tc39/proposal-array-from-async) https://github.com/tc39/proposal-array-from-async/pull/41: avoid double construction of this value ([slides](https://docs.google.com/presentation/d/1mww3D5CO1uebUYiK7l8O5GLjUR98NJYgeHGxQEgnrNA))_ reaches consensus

**Comment by jridgewell** [comment]
[Well-Formed Unicode Strings](https://github.com/tc39/proposal-is-usv-string) (String.prototype.{is,to}WellFormed) for stage 4 ([slides](https://docs.google.com/presentation/d/1_y2n2wK2NIDtUeHZZcb3mxEezRMJ7m_7QBQO50NhxbA/edit#slide=id.p), https://github.com/tc39/ecma262/pull/3039) reaches Stage 4

**Comment by jridgewell** [comment]
[Atomics.waitAsync](https://github.com/tc39/proposal-atomics-wait-async) for Stage 4 (https://github.com/tc39/ecma262/pull/3049) reaches Stage 4

**Comment by jridgewell** [comment]
_[Base64 for Uint8Array](https://github.com/tc39/proposal-arraybuffer-base64) for stage 2 ([slides](https://docs.google.com/presentation/d/1es04vDFcRKSYdj9gsNm2pjgIysHZkBa0k6Ds3kle5to/), [spec](https://tc39.es/proposal-arraybuffer-base64/spec/))_ reaches Stage 2

**Comment by jridgewell** [comment]
_[Symbol Predicates](https://github.com/tc39/proposal-symbol-predicates) needs stage 3 reviewers; confirm https://github.com/tc39/proposal-symbol-predicates/issues/9_ does not reach consensus on throwing, we'll rename the methods to end with "Symbol"

**Comment by jridgewell** [comment]
_[RegExp v flag](https://github.com/tc39/proposal-regexp-v-flag) for Stage 4 (https://github.com/tc39/ecma262/pull/2418, [slides](https://docs.google.com/presentation/d/1pjP06RhOAbYlh-6rYhe3v1SsxD2qLpiWAC2dKDBSJZo/edit))_ reaches Stage 4

**Comment by jridgewell** [comment]
_Decorator field/accessor initializer order (https://github.com/tc39/proposal-decorators/issues/508, [slides](https://slides.com/pzuraq/decorators-field-accessor-initializer-order))_ gains consensus for Option 1, so we'll reverse the run order of initializers to be outermost -> innermost.

**Comment by jridgewell** [comment]
_iterator helpers: should Symbol.iterator fallback be a callable check or an undefined/null check? ([slides](https://docs.google.com/presentation/d/1WlhX7mT7n-lgYmU9RR0AVUmNzFVbhBs2bQtvhjuSgss))_ reaches consensus on Option 1, so we'll change iterator helpers proposal to check nullish instead of callable.

**Comment by jridgewell** [comment]
_iterator helpers: should malformed iterators fail early or fail only when iterated? ([slides](https://docs.google.com/presentation/d/107HP2juNXjuCkoxhUqHZfHiJ0HEGcz-kbraHdpdEiMg))_ gets consensus on Option 3, so iterator helpers will not eagerly validate the next method.

**Comment by jridgewell** [comment]
_[Float16Array](https://github.com/tc39/proposal-float16array) for stage 3 ([slides](https://docs.google.com/presentation/d/1gBVaE4KV9JhRxG_V4_xjLW7P18lnKCDJEIktpi6eIxs/edit), [spec](http://tc39.es/proposal-float16array/))_ reaches Stage 3

**Comment by jridgewell** [comment]
_Decorator Metadata for Stage 3 ([slides](https://slides.com/pzuraq/decorator-metadata-for-stage-3), https://github.com/pzuraq/ecma262/pull/10)_ has general support for the what was discussed:
- `Function.prototype[Symbol.metatdata]` will be added
- Only derived classes will lookup the super's metadata object
- Classes without decorators will not have a metadata object

**Comment by jridgewell** [comment]
_[Intl ZonedDateTimeFormat](https://github.com/FrankYFTang/intl-zoneddatetimeformat) for stage 1 ([slides](https://docs.google.com/presentation/d/1JhEFhB4wUkHfuNeJlCPUaxBv2oGJOKnaF2j8jfmhdi0))_ reaches Stage 1 with a reduced scope for formatting just `ZonedDateTimeFormat` in some ergonomic way

**Comment by zloirock** [comment]
> Decorator Metadata for Stage 3 (slides, pzuraq/ecma262#10) has general support for the what was discussed

But without promotion to stage 3?

**Comment by jridgewell** [comment]
Not yet, the committee asked this to be presented again later in the meeting, but I don't see it scheduled currently.

**Comment by jridgewell** [comment]
_Promise.withResolvers for stage 2 ([repo](https://github.com/peetklecha/proposal-promise-with-resolvers), [slides](https://docs.google.com/presentation/d/1CEh2xgW-KB0Tpz2GQtcJ8nDbWq99d3y8NCwYJw-laSI))_ reaches Stage 2

**Comment by jridgewell** [comment]
_[Source Phase Imports](https://github.com/tc39/proposal-import-reflection) for stage 3 ([slides](https://docs.google.com/presentation/d/1lpJBCe6cgBa5MBtD_Bhfyh92EXcJS72LbStnaoQ4cxo/edit), https://github.com/tc39/proposal-import-reflection/pull/36)_ stays at Stage 2:
- dynamic import changes to a static syntax: `import.<phase>("foo")` instead of `import("foo", { phase: <phase> })`
- We will not restrict the imported identifier

**Comment by jridgewell** [comment]
_[Array.prototype.group](https://github.com/tc39/proposal-array-grouping/) rename for web compatibility ([slides](https://docs.google.com/presentation/d/1QvTThZlYfsXDHGIGR-vAR3AhTbRe9ySukuW-H1ZnjKM/edit#slide=id.p))_ is demoted to Stage 2 due to the change to static methods and accepting iterators, with the expectation that it will come back next meeting for Stage 3 after reviews.

**Comment by michaelficarra** [comment]
@zloirock it is being presented for stage 3 advancement right now

**Comment by jridgewell** [comment]
_Decorator Metadata for Stage 3 ([slides](https://slides.com/pzuraq/decorator-metadata-for-stage-3), https://github.com/pzuraq/ecma262/pull/10)_ reaches Stage 3 with the [above changes](https://github.com/babel/proposals/issues/88#issuecomment-1550313363)

**Comment by ehoogeveen-medweb** [comment]
I miss these summaries. Did they move somewhere else? Is there anywhere I can find meeting notes other than the verbose notes at https://github.com/tc39/notes?

**Comment by ljharb** [comment]
The delegate who does them may not have had time to do them. You can follow the tc39 proposals repo and notes repo for conclusions and stage changes.

closing this one since it’s long past.
