### ISSUE TITLE
How to represent things which have not yet been presented to the committee?

### ISSUE THREAD

**Issue by littledan** [babel/proposals#9]
There are a number of spec proposals which are pretty well written out, and eagerly awaited, which have not yet been presented to TC39. Pattern matching is one of them, and it's included here. I'm working on a private methods proposal which is in a similar state, but it's not represented.

I see a few possible policies here:
- Don't include proposals here until they're presented at TC39 (I thought this was Babel policy)
- Add unpresented proposals when they seem significant enough/have strong user demand (what this page seems to be following)
  - Here, it might be nice to mark the stage distinctly, such as "unpresented" rather than 0.
- Permit any concrete-enough proposal, also marked as unpresented. 
  - This could/should also include proposals which are not by TC39 members, for example [pipeline](https://github.com/gilbert/es-pipeline-operator)
  - These are "pre-stage-0"--not even presented to the committee for basic feedback, I'd suggest leaving them out of the stage 0 preset.

**Comment by hzoo** [comment]
Yeah I'm not sure why we added it earlier but like you said it's a good opportunity to write down our policy.

I'm not sure we should implement a proposal if it's not even presented at TC39? Although, I suppose if the champion is going to present it anyway and it basically automatically goes to Stage 0 then in that case we could allow it. I would probably lean with `#2`? Yeah the current Babel policy is `#1`

**Comment by xtuc** [comment]
I created the pattern matching issue because I saw strong user demand and wanted to keep track of it. 

I think we should permit every proposal to be submited in Babel and for keeping track of it in the early phase. Anyway I don't think a contributor would invest time in Babel if the proposal isn't stable.

**Comment by hzoo** [comment]
Ok I guess there's a difference between tracking it in this repo and accepting a PR for it. Ok, and if we want Babel to be the project that does push proposals forward then it does make sense to lean on the side of tracking these kinds of things for the community/TC39?

**Comment by thejameskyle** [comment]
I think if we know that there is someone on TC39 that is planning on championing it, it can be listed. However, it should probably be marked very differently than the rest. Even in a separate table

**Comment by hzoo** [comment]
Ok let's do that ^ - anyone want to suggest a PR to document this policy + different mark/table?

**Comment by hzoo** [comment]
Kinda mention this in https://github.com/babel/proposals/pull/24, so closing in favor of that
